
title: Documentation
description: >- # this means to ignore newlines until "baseurl:"
  When reviewing a PR for this repo, you can see what the documentation,
  e.g. the storybook, will look like when published for the branches
  named above.
baseurl: "" # the subpath of your site, e.g. /blog
url: "" # the base hostname & protocol for your site, e.g. http://example.com

# Build settings
theme: minima
plugins:
  - jekyll-feed

collections:
  branches:
    output: true
    permalink: /branches/:path/

repo_name: "TBD"


repo: ucsb-cs156-s24/team01-s24-4pm-5
owner: ucsb-cs156-s24
repo_name: team01-s24-4pm-5
pull_requests: [{"author":{"id":"U_kgDOBnFWjw","is_bot":false,"login":"Baimin-Wang","name":""},"headRefName":"BW-LocationController","number":31,"title":"Added Location Controller and Tests","url":"https://github.com/ucsb-cs156-s24/team01-s24-4pm-5/pull/31"},{"author":{"id":"U_kgDOBnFWjw","is_bot":false,"login":"Baimin-Wang","name":""},"headRefName":"BW-LocationService","number":30,"title":"Add Location Service and Tests","url":"https://github.com/ucsb-cs156-s24/team01-s24-4pm-5/pull/30"},{"author":{"id":"U_kgDOBXcy6w","is_bot":false,"login":"winstonwangUCSB","name":""},"headRefName":"Winston-JokeService","number":29,"title":"Add Joke Service and Test","url":"https://github.com/ucsb-cs156-s24/team01-s24-4pm-5/pull/29"}]
