
title: Documentation
description: >- # this means to ignore newlines until "baseurl:"
  When reviewing a PR for this repo, you can see what the documentation,
  e.g. the storybook, will look like when published for the branches
  named above.
baseurl: "" # the subpath of your site, e.g. /blog
url: "" # the base hostname & protocol for your site, e.g. http://example.com

# Build settings
theme: minima
plugins:
  - jekyll-feed

collections:
  branches:
    output: true
    permalink: /branches/:path/

repo_name: "TBD"


repo: ucsb-cs156-s24/team01-s24-4pm-5
owner: ucsb-cs156-s24
repo_name: team01-s24-4pm-5
pull_requests: [{"author":{"id":"U_kgDOB2-2pQ","is_bot":false,"login":"nevetsle","name":""},"headRefName":"Steven-HomeController","number":24,"title":"Added HomeController & Tests","url":"https://github.com/ucsb-cs156-s24/team01-s24-4pm-5/pull/24"},{"author":{"id":"U_kgDOB2-2pQ","is_bot":false,"login":"nevetsle","name":""},"headRefName":"Steven-PublicHoliday-Controller","number":23,"title":"Add PublicHoliday Service & Controller","url":"https://github.com/ucsb-cs156-s24/team01-s24-4pm-5/pull/23"},{"author":{"id":"U_kgDOB2-2pQ","is_bot":false,"login":"nevetsle","name":""},"headRefName":"Steven-PublicHoliday","number":22,"title":"Add PublicHoliday Services & Tests","url":"https://github.com/ucsb-cs156-s24/team01-s24-4pm-5/pull/22"},{"author":{"id":"U_kgDOBckqqw","is_bot":false,"login":"CongruiDu","name":"RayDu"},"headRefName":"RD-ZipcodeService","number":21,"title":"Add ZipCode Service and Tests","url":"https://github.com/ucsb-cs156-s24/team01-s24-4pm-5/pull/21"},{"author":{"id":"U_kgDOBnFWjw","is_bot":false,"login":"Baimin-Wang","name":""},"headRefName":"BW-Location","number":20,"title":"Added Location Service and Tests","url":"https://github.com/ucsb-cs156-s24/team01-s24-4pm-5/pull/20"},{"author":{"id":"U_kgDOBdCCBA","is_bot":false,"login":"jasontnguyen","name":"Jason Nguyen"},"headRefName":"JN-Tides-Controller","number":19,"title":"Add Tides Service and Controller","url":"https://github.com/ucsb-cs156-s24/team01-s24-4pm-5/pull/19"},{"author":{"id":"U_kgDOBdCCBA","is_bot":false,"login":"jasontnguyen","name":"Jason Nguyen"},"headRefName":"JN-Tides-Service","number":18,"title":"Add Tides Service and Tests","url":"https://github.com/ucsb-cs156-s24/team01-s24-4pm-5/pull/18"}]
